name: BlinqReleaseBot
description: 'The Blinq automated release bot'
branding:
  icon: 'rocket'
  color: orange
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  org:
    description: 'GitHub Organization'
    required: true
  repo:
    description: 'GitHub Repository'
    required: true
  release_title:
    description: 'Release title'
    required: false
